CREATE ROLE rms_app WITH LOGIN PASSWORD 'Owner@123' NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER ROLE rms_app SET client_encoding TO 'UTF8';
ALTER ROLE rms_app SET timezone TO 'UTC';

CREATE DATABASE rms_dev OWNER rms_app;
CREATE DATABASE rms_test OWNER rms_app;
CREATE DATABASE rms_prod OWNER rms_app;

GRANT ALL PRIVILEGES ON DATABASE rms_dev TO rms_app;
GRANT ALL PRIVILEGES ON DATABASE rms_test TO rms_app;
GRANT ALL PRIVILEGES ON DATABASE rms_prod TO rms_app;
